# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 03:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'original_manager'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'base_manager_name': 'original_manager', 'default_manager_name': 'original_manager'},
        ),
        migrations.AlterModelManagers(
            name='article',
            managers=[
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='tag',
            managers=[
                ('original_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
