# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20171024_2225'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['tenant'], name='articles_ar_tenant__44006e_idx'),
        ),
    ]
