# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_schema_tenants', '0001_initial'),
        ('shared_schema_tenants_custom_data', '0002_auto_20171118_1223'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tenantspecificfieldcharpivot',
            index_together=set([('tenant', 'id')]),
        ),
        migrations.AlterIndexTogether(
            name='tenantspecificfielddatepivot',
            index_together=set([('tenant', 'id')]),
        ),
        migrations.AlterIndexTogether(
            name='tenantspecificfielddatetimepivot',
            index_together=set([('tenant', 'id')]),
        ),
        migrations.AlterIndexTogether(
            name='tenantspecificfieldfloatpivot',
            index_together=set([('tenant', 'id')]),
        ),
        migrations.AlterIndexTogether(
            name='tenantspecificfieldintegerpivot',
            index_together=set([('tenant', 'id')]),
        ),
        migrations.AlterIndexTogether(
            name='tenantspecificfieldtextpivot',
            index_together=set([('tenant', 'id')]),
        ),
        migrations.AlterIndexTogether(
            name='tenantspecifictablespermission',
            index_together=set([('tenant', 'id')]),
        ),
        migrations.AlterIndexTogether(
            name='tenantspecifictablesrelationship',
            index_together=set([('tenant', 'id')]),
        ),
    ]
