# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import shared_schema_tenants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shared_schema_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='_extra_data',
            field=models.TextField(blank=True, default='{"logo": null, "number_of_employees": 0, "is_non_profit": false}', null=True, validators=[shared_schema_tenants.validators.validate_json]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='_settings',
            field=models.TextField(blank=True, default='{"notify_users_by_email": true}', null=True, validators=[shared_schema_tenants.validators.validate_json]),
        ),
    ]
